Repository DIT112-V21/group-06, pull requests merged in 2021-04, with the labels that each got.

#7 React project base added for the GUI
  .gitignore
  README.md
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/App.test.js
  src/index.css
  src/index.js
  src/reportWebVitals.js
  src/setupTests.js
Labels: Sprint 1

#6 Basic obstacle avoidance for #US1
  arduino/smartcar/smartcar.ino
Labels: Sprint 1

#8 Mqtt controller
  .github/workflows/arduino-build.yml
  arduino/smartcar/smartcar.ino
  package-lock.json
  package.json
  src/publisher.js
Labels: Sprint 1

#19 gui and mqtt connected
  package-lock.json
  public/index.html
  src/App.css
  src/App.js
  src/Components/Button.js
  src/Components/CarControl.js
  src/Css/CarControl.css
  src/Css/index.css
  src/index.js
  src/publisher.js
Labels: Sprint 1

#21 Added multiple page support
  package-lock.json
  package.json
  src/Components/App.js
  src/Components/Home.js
  src/Components/Main.js
  src/index.js
Labels: Sprint 2

#23 Basic database creation
  src/DatabaseController.js
  src/elephantsql.js
Labels: Sprint 2

#26 Video stream in gui
  .github/workflows/arduino-build.yml
  .vscode/settings.json
  arduino/smartcar/smartcar.ino
  package-lock.json
  package.json
  public/logo192.png
  public/logo512.png
  src/Components/CarControl.js
  src/Css/CarControl.css
  src/MqttController.js
  src/publisher.js
Labels: Sprint 2

#27 Elephantsql.js is redundant
  src/elephantsql.js
Labels: duplicate
